PortA:
  device: color-sensor
  enable_lights: True
  light_qos: best-effort

PortB:
  device: ultrasonic-sensor
  enable_lights: True
  light_qos: best-effort

PortE:
  device: force-sensor

hub:
  hub_program_cycle: 10
  enable_imu: False
  enable_battery_management: False
  enable_button: False
  enable_speaker: False
  opening: True
